version: "3.8"

services:
  app:
    container_name: localstack-example-app
    build:
      context: .
    ports:
      - "9000:9000"
    environment:
      LISTEN_PORT: ":9000"
    volumes:
      - ./src/:/go/app
      - go_dir:/go

volumes:
  db_data:
  go_dir:
